apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
  labels:
    app: boardgame
spec:
  replicas: 2
  selector:
    matchLabels:
      app: boardgame
  template:
    metadata:
      labels:
        app: boardgame
    spec:
      containers:
      - name: can1
        image: sidhulavhare/boardgame:latest
        ports:
        - containerPort: 8080

----
apiVersion: v1
kind: Service
metadata:
  name: myservice
spec:
  selector:
    app: boardgame
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer

